Repository mohitahlawat2001/Loco-Musica, pull requests merged in 2024-10, with the labels that each got.

#9 Duplicate Food Item Added to Cart #6
  src/components/Cart.js
  src/components/RestaurantMenu.js
Labels: hacktoberfest-accepted

#14 Search Bar Updated
  package-lock.json
  package.json
  src/components/Body.js
Labels: hacktoberfest-accepted

#17 Improved Footer design #13
  package-lock.json
  package.json
  src/components/Footer.js
Labels: hacktoberfest-accepted

#8 Add geo location
  src/Constants.js
  src/components/Body.js
Labels: good first issue, hacktoberfest, hacktoberfest-accepted

#33 Styled scrollbar
  index.css
Labels: hacktoberfest

#31 User can regulate the quanitity of food items from menu page itself
  src/components/Cart.js
  src/components/RestaurantMenu.js
  src/utils/cartSlice.js
Labels: hacktoberfest

#27 responsiveness done
  src/components/Body.js
  src/components/Cart.js
  src/components/Header.js
  src/components/Login.js
Labels: hacktoberfest, hacktoberfest-accepted

#40 Added Backend for storing user data , orders and for authentication
  Backend/app.js
  Backend/controllers/control.js
  Backend/database/database.js
  Backend/middlewares/auth.js
  Backend/models/orders.js
  Backend/models/user.js
  Backend/package-lock.json
  Backend/package.json
  Backend/routes/buyer.js
  Backend/utils/features.js
  package-lock.json
  package.json
  src/app.js
  src/components/About.js
  src/components/Cart.js
  src/components/Footer.js
  src/components/Header.js
  src/components/Login.js
  src/components/Profile.js
Labels: enhancement, good first issue, hacktoberfest

#85 broken link: added license file
  LICENSE
Labels: hacktoberfest-accepted
